sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    access-key-id: LTAI5t7Eu1sdhP97iomnjsFg
    access-key-secret: ulINGrwm2oBsB4A7ML7MKhbb52RlAH
    bucket-name: song-hao-java
    endpoint: oss-cn-beijing.aliyuncs.com
  redis:
    host: localhost
    port: 6379
    password: 123456
  wechat:
    appid: wx8522ac9713147232
    secret: 62a59869cb4987fecff205eba872b928